<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:rda="http://www.records.nsw.gov.au/schemas/RDA" xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml" xmlns:aml="http://schemas.microsoft.com/aml/2001/core" xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint" version="1.0">
  <xsl:template name="boilerplate">
    <xsl:param name="hascustody"/>
    <w:p>
      <w:pPr>
        <w:pStyle w:val="Heading1"/>
        <w:rPr>
          <w:sz w:val="24"/>
        </w:rPr>
      </w:pPr>
      <w:r>
        <w:rPr>
          <w:sz w:val="24"/>
        </w:rPr>
        <w:br w:type="page"/>
      </w:r>
      <w:r>
        <w:rPr>
          <w:sz w:val="24"/>
        </w:rPr>
        <w:t>
          <xsl:text>About the </xsl:text>
          <xsl:value-of select="$AUTHORITY_TYPE"/>
        </w:t>
      </w:r>
    </w:p>
    <wx:sub-section>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Heading2"/>
        </w:pPr>
        <w:r>
          <w:t>
            <xsl:text>Purpose of the authority</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>The purpose of this </xsl:text><xsl:value-of select="$AUTHORITY_TYPE_LC"/><xsl:text> is to identify those records created and maintained by NSW public offices which are required as State archives and to provide approval for the destruction of certain other records created and maintained by NSW public offices, after minimum retention periods have been met. </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:br/>
        </w:r>
        <w:r>
          <w:br/>
          <w:t>
            <xsl:text>The approval for disposal given by this authority is given under the provisions of the </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
            <w:i-cs/>
          </w:rPr>
          <w:t>
            <xsl:text>State Records Act 1998</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text> only and does not override any other obligations of an organisation to retain records.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
    </wx:sub-section>
    <wx:sub-section>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Heading2"/>
        </w:pPr>
        <w:r>
          <w:t>
            <xsl:text>The retention and disposal of State records</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:rPr>
            <w:lang w:val="EN-US"/>
          </w:rPr>
          <w:t>
            <xsl:text>The records retention and disposal practices outlined in this authority are approved under section 21(2)(c) of the </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
            <w:lang w:val="EN-US"/>
          </w:rPr>
          <w:t>
            <xsl:text>State Records Act 1998 (NSW).</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:lang w:val="EN-US"/>
          </w:rPr>
          <w:t>
            <xsl:text> Part 3 (Protection of State Records) of the Act provides that records are not to be disposed of without the consent of the State Archives and Records Authority of New South Wales (State Archives and Records NSW) with certain defined exceptions. These exceptions include an action of disposal which is positively required by law, or which takes place in accordance with a normal administrative practice (NAP) of which State Archives and Records NSW does not disapprove. </xsl:text>
          </w:t>
        </w:r>
        <aml:annotation aml:id="0" w:type="Word.Bookmark.Start" w:name="OLE_LINK1"/>
        <aml:annotation aml:id="1" w:type="Word.Bookmark.Start" w:name="OLE_LINK2"/>
        <w:r>
          <w:rPr>
            <w:lang w:val="EN-US"/>
          </w:rPr>
          <w:t>
            <xsl:text>Advice on the State Records Act can be obtained from State Archives and Records NSW.</xsl:text>
          </w:t>
        </w:r>
        <aml:annotation aml:id="0" w:type="Word.Bookmark.End"/>
        <aml:annotation aml:id="1" w:type="Word.Bookmark.End"/>
        <w:r>
          <w:t> </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>The authority sets out how long the different classes of records generated by an organisation must be kept to meet its legal, operational and other requirements, and whether the records are to be kept as State archives. State Archives and Records NSW reviews and approves organisations' retention and disposal authorities under the </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>State Records Act</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text>. </xsl:text>
            <xsl:if test="$AUTHORITY_TYPE='Functional Retention and Disposal Authority'">
            <xsl:text>It is the duty of a public office, in submitting a draft retention and disposal authority for approval, to disclose to State Archives and Records NSW any information which affects the retention of the records covered by the authority.</xsl:text>
            </xsl:if>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>State Archives and Records NSW’s decisions take into account both the administrative requirements of public offices in discharging their functional responsibilities and the potential research use of the records by the NSW Government and the public. </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text>One of State Archives and Records NSW’s functions is to identify and preserve records as State archives. These are records which document the authority and functions of Government, its decision-making processes and the implementation and outcomes of those decisions, including the nature of their influence and effect on communities and individual lives. Criteria for the identification of State archives are listed in </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>Building the Archives: Policy on records appraisal and the identification of State archives</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text>. The Policy also explains the roles and responsibilities of State Archives and Records NSW and of public offices in undertaking appraisal processes and disposal activities.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
    </wx:sub-section>
    <wx:sub-section>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Heading2"/>
        </w:pPr>
        <w:r>
          <w:t>
            <xsl:text>Implementing the authority</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>This </xsl:text><xsl:value-of select="$AUTHORITY_TYPE_LC"/><xsl:text> covers records controlled by the public office and applies only to the records or classes of records described in the authority. </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text>The authority should be implemented as part of the records management program of the organisation. Two primary objectives of this program are to ensure that records are kept for as long as they are of value to the organisation and its stakeholders and to enable the destruction or other disposal of records once they are no longer required for business or operational purposes. </xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>The implementation process entails use of the authority to sentence records. Sentencing is the examination of records in order to identify the disposal class in the authority to which they belong. This process enables the organisation to determine the appropriate retention period and disposal action for the records. For further advice see </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>Implementing a retention and disposal authority</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text>.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>Where the format of records has changed (for example, from paper-based to electronic) this does not prevent the disposal decisions in the authority from being applied to records which perform the same function. The information contained in non paper-based or technology dependant records must be accessible for the periods prescribed in the classes. Where a record is copied, either onto microform or digitally imaged, the original should not be disposed of without authorisation (see the </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>General Retention and Disposal Authority – Original or source records that have been copied</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text>). Public offices will need to ensure that any software, hardware or documentation required to gain continuing access to technology dependent records is available for the periods prescribed.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
    </wx:sub-section>
    <wx:sub-section>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Heading2"/>
        </w:pPr>
        <w:r>
          <w:t>
            <xsl:text>Disposal action</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:rPr>
            <w:b/>
            <w:i/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:b/>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>Records required as State archives</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>Records which are to be retained as State archives are identified with the disposal action 'Required as State archives'. </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text>Records that are identified as being required as State archives should be stored in controlled environmental conditions and control of these records should be transferred to State Archives and Records NSW when they are no longer in use for official purposes. </xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>The transfer of control of records as State archives may, or may not, involve a change in custodial arrangements. Records can continue to be managed by the public office under a distributed management agreement. Public offices are encouraged to make arrangements with State Archives and Records NSW regarding the management of State archives.</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:br/>
        </w:r>
        <w:r>
          <w:br/>
          <w:t>
            <xsl:text>Transferring records identified as State archives and no longer in use for official purposes to State Archives and Records NSW should be a routine and systematic part of a public office's records management program. If the records are more than 25 years old and are still in use for official purposes, then a 'still in use determination' should be made.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:keepNext/>
          <w:rPr>
            <w:b/>
            <w:i/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:b/>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>Records approved for destruction</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:spacing w:before="0"/>
        </w:pPr>
        <w:r>
          <w:t>
            <xsl:text>Records that have been identified as being approved for destruction may only be destroyed once a public office has ensured that all other requirements for retaining the records are met. Retention periods set down in this authority are </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>minimum</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text> periods only and a public office should keep records for a longer period if necessary. Reasons for longer retention can include legal requirements, administrative need, government directives and changing social or community expectations. A public office </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
            <w:b/>
          </w:rPr>
          <w:t>
            <xsl:text>must not</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text> dispose of any records where the public office is aware of possible legal action (including legal discovery, court cases, formal applications for access) where the records may be required as evidence.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>Once all requirements for retention have been met, destruction of records should be carried out in a secure and environmentally sound way. Relevant details of the destruction should be recorded. See </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
          </w:rPr>
          <w:t>
            <xsl:text>Destruction of records: a practical guide</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <xsl:if test="$AUTHORITY_TYPE='Functional Retention and Disposal Authority'">
      <w:p>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>Organisations should review functional retention and disposal authorities regularly to ensure that they remain relevant as the organisation’s functions and activities, operating environment and requirements for records change.</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text> Retention requirements may change over time. This can occur when:</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:listPr>
            <w:ilvl w:val="0"/>
            <w:ilfo w:val="1"/>
            <wx:t wx:val="·" wx:wTabBefore="360" wx:wTabAfter="270"/>
            <wx:font wx:val="Symbol"/>
          </w:listPr>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>business needs or practices change </xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:listPr>
            <w:ilvl w:val="0"/>
            <w:ilfo w:val="1"/>
            <wx:t wx:val="·" wx:wTabBefore="360" wx:wTabAfter="270"/>
            <wx:font wx:val="Symbol"/>
          </w:listPr>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>new laws, regulations or standards are introduced </xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:listPr>
            <w:ilvl w:val="0"/>
            <w:ilfo w:val="1"/>
            <wx:t wx:val="·" wx:wTabBefore="360" wx:wTabAfter="270"/>
            <wx:font wx:val="Symbol"/>
          </w:listPr>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>new technology is implemented </xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:listPr>
            <w:ilvl w:val="0"/>
            <w:ilfo w:val="1"/>
            <wx:t wx:val="·" wx:wTabBefore="360" wx:wTabAfter="270"/>
            <wx:font wx:val="Symbol"/>
          </w:listPr>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>government administration is restructured and functions are moved between entities, or </xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:listPr>
            <w:ilvl w:val="0"/>
            <w:ilfo w:val="1"/>
            <wx:t wx:val="·" wx:wTabBefore="360" wx:wTabAfter="270"/>
            <wx:font wx:val="Symbol"/>
          </w:listPr>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>unforeseen or new community expectations become apparent.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:pPr>
          <w:spacing w:before="100" w:before-autospacing="on" w:after="100" w:after-autospacing="on"/>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
        </w:pPr>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>State Archives and Records NSW recommends that organisations check any functional retention and disposal authorities </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:b-cs/>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text>more than 5 years old</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:lang w:fareast="EN-AU"/>
          </w:rPr>
          <w:t>
            <xsl:text> to ensure that the retention periods and disposal actions remain relevant.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      </xsl:if>
      <w:p>
        <w:pPr>
          <w:spacing w:before="0"/>
        </w:pPr>
        <w:r>
          <w:t>
            <xsl:text>Regardless of whether a record has been approved for destruction or is required as a State archive, a public office or an officer of a public office </xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:rPr>
            <w:i/>
            <w:b/>
          </w:rPr>
          <w:t>
            <xsl:text>must not</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:t>
            <xsl:text> permanently transfer possession or ownership of a State record to any person or organisation without the explicit approval of State Archives and Records NSW.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
    </wx:sub-section>
    <xsl:if test="$hascustody='true'">
      <wx:sub-section>
        <w:p>
          <w:pPr>
            <w:pStyle w:val="Heading2"/>
          </w:pPr>
          <w:r>
            <w:t>
              <xsl:text>Custody</xsl:text>
            </w:t>
          </w:r>
        </w:p>
        <w:p>
          <w:pPr>
            <w:spacing w:before="0"/>
          </w:pPr>
          <w:r>
            <w:t>
              <xsl:text>The custody column in the </xsl:text><xsl:value-of select="$AUTHORITY_TYPE_LC"/><xsl:text> is designed to assist public offices in identifying storage requirements or transfer arrangements for records identified as State archives (i.e. with a Disposal action of ‘Required as State archives’). The directions in this column are recommendations only and are </xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:i/>
            </w:rPr>
            <w:t>
              <xsl:text>not</xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:t>
              <xsl:text> mandatory. The type of information may include directions on how long records should be retained in the office and how long they should be kept in off</xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:noBreakHyphen/>
            <w:t>
              <xsl:text>site, off-line or secondary storage prior to their transfer as State archives. A recommendation to retain records in the organisation for more than 25 years does not imply that a </xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:i/>
            </w:rPr>
            <w:t>
              <xsl:text>still in use determination</xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:t>
              <xsl:text> (see Part 4, Section 28 of the </xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:i/>
            </w:rPr>
            <w:t>
              <xsl:text>State Records Act 1998</xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:t>
              <xsl:text>) or that a distributed management agreement (see Part 4, Section 30 of the </xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:rPr>
              <w:i/>
            </w:rPr>
            <w:t>
              <xsl:text>State Records Act 1998</xsl:text>
            </w:t>
          </w:r>
          <w:r>
            <w:t>)</w:t>
          </w:r>
          <w:r>
            <w:t>
              <xsl:text> has been approved by State Archives and Records NSW. Advice on arrangements for managing and transferring State archives can be obtained from State Archives and Records NSW.</xsl:text>
            </w:t>
          </w:r>
        </w:p>
      </wx:sub-section>
    </xsl:if>
    <wx:sub-section>
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Heading2"/>
        </w:pPr>
        <w:r>
          <w:t>Administrative change</w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>This </xsl:text><xsl:value-of select="$AUTHORITY_TYPE_LC"/><xsl:text> has been designed to link records to the functions they document rather than to organisational structure. This provides for a stable retention and disposal authority that is less affected by administrative change. </xsl:text>
            <xsl:if test="$AUTHORITY_TYPE='Functional Retention and Disposal Authority'">
                <xsl:text>The movement of specified functions between branches or units within the public office does not require the authority to be resubmitted to State Archives and Records NSW for approval. </xsl:text>
            </xsl:if> 
             <xsl:text>However, when functions move from one public office to another the public office that inherits the new function should contact State Archives and Records NSW to discuss use of any existing retention and disposal authority approved for use by a predecessor organisation.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
    </wx:sub-section>
    <wx:sub-section>
      <xsl:if test="$AUTHORITY_TYPE='Functional Retention and Disposal Authority'">
      <w:p>
        <w:pPr>
          <w:pStyle w:val="Heading2"/>
        </w:pPr>
        <w:r>
          <w:t>
            <xsl:text>Amendment and review of this authority</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>State Archives and Records NSW must approve any amendment to this authority. Public offices that use the authority should advise State Archives and Records NSW of any proposed changes or amendments to the authority.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>State Archives and Records NSW recommends a review of this authority after five years to establish whether its provisions are still appropriate. Either the public office or State Archives and Records NSW may propose a review of the authority at any other time, particularly in the case of change of administrative arrangements, procedures or to operating environments which are likely to affect the value of the records covered by this authority.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>In all cases the process of review will involve consultation between State Archives Records NSW and the public office. If the process of review reveals that this authority requires amendment, the necessary amendments should be made and approved.</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      </xsl:if>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>Contact Information</xsl:text>
          </w:t>
        </w:r>
      </w:p>
      <w:p>
        <w:r>
          <w:t>
            <xsl:text>State Archives and Records NSW</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:br/>
          <w:t>
            <xsl:text>PO Box 516</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:br/>
          <w:t>
            <xsl:text>Kingswood NSW 2747</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:br/>
          <w:t>
            <xsl:text>Telephone: (02) 9673 1788</xsl:text>
          </w:t>
        </w:r>
        <w:r>
          <w:br/>
          <w:t>
            <xsl:text>E-mail: </xsl:text>
          </w:t>
        </w:r>
        <w:hlink w:dest="mailto:govrec@records.nsw.gov.au">
          <w:r>
            <w:rPr>
              <w:rStyle w:val="Hyperlink"/>
            </w:rPr>
            <w:t>
              <xsl:text>govrec@records.nsw.gov.au</xsl:text>
            </w:t>
          </w:r>
        </w:hlink>
      </w:p>
      <xsl:choose>
        <xsl:when test="rda:Context[@type='guidelines for use']">
          <w:p>
            <w:pPr>
              <w:pStyle w:val="Heading1"/>
              <w:rPr>
                <w:sz w:val="24"/>
              </w:rPr>
            </w:pPr>
            <w:r>
              <w:rPr>
                <w:sz w:val="24"/>
              </w:rPr>
              <w:br w:type="page"/>
            </w:r>
            <w:r>
              <w:rPr>
                <w:sz w:val="24"/>
              </w:rPr>
              <w:t>
                <xsl:text>Understanding and using the authority</xsl:text>
              </w:t>
            </w:r>
          </w:p>
          <xsl:for-each select="rda:Context[@type='guidelines for use']">
          <w:p>
            <w:pPr>
              <w:pStyle w:val="Heading2"/>
            </w:pPr>
            <w:r>
              <w:t>
                <xsl:value-of select="rda:ContextTitle"/>
              </w:t>
            </w:r>
            </w:p>
            <xsl:for-each select="rda:ContextContent">
                <xsl:apply-templates select="rda:Paragraph"/>
              </xsl:for-each>
          </xsl:for-each>
        </xsl:when>
        <xsl:otherwise>
          <w:p/>
        </xsl:otherwise>
      </xsl:choose>
      <w:p>
        <w:pPr>
          <w:sectPr>
            <w:ftr w:type="odd">
              <xsl:call-template name="footer"/>
            </w:ftr>
            <w:ftr w:type="first">
              <w:p>
                <w:pPr>
                  <w:pStyle w:val="Footer"/>
                  <w:pBdr>
                    <w:top w:val="none" w:sz="0" wx:bdrwidth="0" w:space="0" w:color="auto"/>
                  </w:pBdr>
                </w:pPr>
              </w:p>
            </w:ftr>
            <xsl:choose>
              <xsl:when test="$ORIENTATION='portrait'">
                <w:pgSz w:w="11907" w:h="16840" w:code="9"/>
                <w:pgMar w:top="1418" w:right="1418" w:bottom="1418" w:left="1418" w:header="567" w:footer="567" w:gutter="0"/>
              </xsl:when>
              <xsl:otherwise>
                <w:pgSz w:w="16840" w:h="11907" w:orient="landscape" w:code="9"/>
                <w:pgMar w:top="1418" w:right="1134" w:bottom="1418" w:left="1134" w:header="567" w:footer="567" w:gutter="0"/>
              </xsl:otherwise>
            </xsl:choose>
            <w:paperSrc w:first="7" w:other="7"/>
            <w:pgNumType w:start="1"/>
            <w:cols w:space="720"/>
            <w:titlePg/>
          </w:sectPr>
        </w:pPr>
      </w:p>
    </wx:sub-section>
  </xsl:template>
</xsl:stylesheet>
